# -*- coding: utf-8 -*-
"""Copy of sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdEYNcI43BEPrDUsi_hQZs_5RXEO-V53
"""

pip install vaderSentiment

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
sentences=["you are a loser but winner in life"]
analyzer=SentimentIntensityAnalyzer()
for sentence in sentences:
  a=analyzer.polarity_scores(sentence)
  print("{:-<65} {}" .format(sentence,str(a)))